# Aplicación 2 nginx con dos servicios

volumes:
  vol_nginx:

services:
  
  nginx-1:
    image: nginx
    ports:
      - 8081:80
    volumes:
      - vol_nginx:/mi-vol
  
  nginx-2:
    image: nginx
    ports:
      - 8082:80
    volumes:
      - vol_nginx:/mi-vol
    
